lukaszewczak/WDP-2001-01

- package-lock.json
- src/components/common/ProductBox/ProductBox.module.scss
Branch zawiera ukrycie buttonów "Add to cart" oraz "Quick view". Pokazują się one tylko po najechaniu na całego boksa z produktem. Zmienia się wtedy również tło ceny na $primary.
https://projects.kodilla.com/browse/WDP200101-4
> add hover-visible buttons on cart and change price background

- src/components/features/ProductSearch/ProductSearch.module.scss
- src/components/layout/MenuBar/MenuBar.js
- src/components/layout/MenuBar/MenuBar.module.scss
Dodałem responsywność do głównego menu aplikacji według wytycznych.
https://projects.kodilla.com/browse/WDP200101-14
> add responsive to menubar

- src/components/common/Button/Button.js
- src/components/common/Button/Button.module.scss
- src/components/common/ProductBox/ProductBox.js
- src/components/features/NewFurniture/NewFurniture.js
- src/redux/initialState.js
Ostylowałem buttony "ulubiony" oraz "dodany do porónania" gdy są aktywne. 
https://projects.kodilla.com/browse/WDP200101-5
> add favourited and addToCompare buttons styles if are selected

- src/components/features/FeatureBoxes/FeatureBoxes.js
- src/components/features/FeatureBoxes/FeatureBoxes.module.scss
Dodałem responsywnośc do kart korzyści według wytycznych klienta
https://projects.kodilla.com/browse/WDP200101-16
> add responsive to benefit cards

- src/components/features/NewFurniture/NewFurniture.js
Dodałem responsywnośc w zakładce "new furniture" w tej sekcji pozostało jeszcze zrobić responsywność dla ala menu z wyborem odpowiedniej kategorii.
https://projects.kodilla.com/browse/WDP200101-17
> add resposive to new furniture section

- src/components/layout/CompanyClaim/CompanyClaim.js
- src/components/layout/CompanyClaim/CompanyClaim.module.scss
- src/components/layout/TopBar/TopBar.js
- src/components/layout/TopBar/TopBar.module.scss
Task https://projects.kodilla.com/browse/WDP200101-15
RWD - top bar i banner. Comp: TopBar i CompanyClaim zmodyfikowane.
> Wdp200101 15

- src/components/layout/CompanyClaim/CompanyClaim.module.scss
Zmieniłem style związane z wyświetlaniem liczby w koszyku.
> Change style CompanyClaim.module.scss

- src/styles/_hover.scss
- src/styles/global.scss
Do katalogu projektu src/styles został dodany nowy plik styli _hover.scss, gdzie jest zdefiniowany @extend z animacją, dla wszystkich elementów używających pseudo-klasy ":hover". Domyślne czasy animacji ustawione są na 250ms. W pliku global.scss plik _hover.scss jest importowany.
> add file _hover.scss and change file global.scss

- src/components/features/NewFurniture/NewFurniture.js
- src/components/features/NewFurniture/NewFurniture.module.scss
Dot. RWD PanelBar'u sekcji "New Furniture".
https://projects.kodilla.com/browse/WDP200101-44
> WDP200101-44

- src/components/features/Brands/Brands.js
Dot. RWD sekcji "Brands".
Zmieniono responsywność brandów na bardziej spójny wygląd.
https://projects.kodilla.com/browse/WDP200101-32
> WDP200101-32

- src/components/features/Sale/Sale.js
Dodałem responsywność do sekcji promocje
"Na szerokościach, gdzie trzy boxy nie mieszczą się obok siebie, należy ułożyć je jeden pod drugim (największy na górze, pod nim dwa mniejsze)."
https://projects.kodilla.com/browse/WDP200101-26
> WDP200101-26

- package.json
Cześć, to jest moja próba dodania konfiguracji na podstawie przykładów wyczytanych w dokumentacji lint-staged. Docelowo kod html i scss powinien być sprawdzany w momencie robienia commita.
> add lint-staged config for scss and html

- src/components/layout/CompanyClaim/CompanyClaim.module.scss
Dot. wycentrowania koszyka.
https://projects.kodilla.com/browse/WDP200101-49
> WDP200101-49

- src/components/layout/CompanyClaim/CompanyClaim.js
Dodałem przekierowywanie do strony głównej po kliknięciu w logo w top barze
https://projects.kodilla.com/browse/WDP200101-43
> WDP200101-43 

- .env
- .eslintrc
Dodałem zmienną środowiskową `EXTEND_ESLINT` aby ujednolicić konfigurację ESLinta.
> add EXTEND_ESLINT to true

- src/components/common/Swipeable/Swipeable.js
W pliku Swipeable.js został dodany fragment kodu kontrolujący na co ma wskazywać currenPage, gdy w wyniku wielu kliknięć wyjdzie poza swój zakres.
> Change Swipeable.js

- src/components/common/BlogBox/BlogBox.js
- src/components/common/BlogBox/BlogBox.module.scss
- src/components/common/BlogBox/BlogBoxContainer.js
- src/components/features/LatestBlog/LatestBlog.js
- src/components/features/LatestBlog/LatestBlog.module.scss
- src/components/features/LatestBlog/LatestBlogContainer.js
- src/components/views/Homepage/Homepage.js
- src/redux/initialState.js
- src/styles/settings.scss
Zadanie polegalo na zrobieniu sekcji LatstBlog. https://projects.kodilla.com/browse/WDP200101-35
W tym celu stworzylem 2 komponenty: LastBlog w folderze features i BlogBox w folderze common
> Wdp200101 35

- src/components/views/Homepage/Homepage.js
Dot. usunięcia powtórzonej sekcji "Feedback".
https://projects.kodilla.com/browse/WDP200101-62
> WDP200101-62

- src/components/features/FeatureBoxes/FeatureBoxes.module.scss
- src/components/features/Gallery/Gallery.module.scss
- src/components/features/Promoted/Promoted.module.scss
- src/components/features/Sale/Sale.module.scss
Zadanie miało na celu ujednolicenie odstępów pomiędzy różnymi sekcjami strony projektu i likwidację zbyt dużych odstępów. 
https://projects.kodilla.com/browse/WDP200101-57
> Change styles section files

- .stylelintrc.json
- package.json
- src/components/common/BlogBox/BlogBox.module.scss
- src/components/common/HotDealsProductBox/HotDealsProductBox.module.scss
- src/components/common/PromotedProductBox/PromotedProductBox.module.scss
- src/components/features/LatestBlog/LatestBlog.module.scss
- src/components/features/ProductSearch/ProductSearch.module.scss
- src/components/features/Promoted/Promoted.module.scss
- src/components/features/Sale/Sale.module.scss
- src/components/layout/MenuBar/MenuBar.module.scss
- src/styles/_hover.scss
Zadanie polegalo na dodaniu reguly odpowiadajacej za maksymalną glebokosc zagniezdzenia (3) z opcja  ignorowania pseudo klas.
https://projects.kodilla.com/browse/WDP200101-56
> WDP200101 56

- src/components/features/LatestBlog/LatestBlog.module.scss
Poprawione zostało wyświetlanie się PanelBara w sekcji LatestBlog.
https://projects.kodilla.com/browse/WDP200101-64
> Change style LatesBlog

- src/components/common/Icons/Icons.js
- src/components/common/Icons/Icons.module.scss
- src/components/common/Icons/IconsContainer.js
- src/components/features/Gallery/Gallery.js
dodano możliwość dodawania do ulubionych produktu w komponencie <Gallery />
Zawiera w sobie również taska `WDP200101-61`, który zakładał dodanie produktu do listy do porówniania.
> Wdp200101 63

- src/components/common/BlogBox/BlogBox.js
- src/components/common/Icons/Icons.js
- src/components/common/Swipeable/Swipeable.js
- src/components/features/LatestBlog/LatestBlog.js
- src/components/features/ProductSearch/ProductSearch.js
- src/components/features/ProductSearch/ProductSearch.module.scss
- src/components/views/ProductPage/ProductPage.test.js
- src/components/views/ProductPage/ProductPagePhoto.js
- src/serviceWorker.js
Z racji problemów w poprzednim pr wolałem stworzyć nowy i zrobić wszystko od nowa.
Musiałem usunąć wanirngi w konsoli.
https://projects.kodilla.com/browse/WDP200101-46
> Wdp200101 46 fix

- src/components/common/GalleryBox/GalleryBox.js
- src/components/common/GalleryBox/GalleryBox.module.scss
- src/components/features/Gallery/Gallery.js
- src/components/features/Gallery/Gallery.module.scss
- src/components/features/Gallery/GalleryContainer.js
- src/redux/categoriesRedux.js
- src/redux/initialState.js
Zadanie polegalo na stworzeniu funkcjonalnosci w sekcji Galeria. Zostalo dodane wybieranie po kliknieciu w kategorie a takze dodany zostal slider z opcja wyswietlanie do 6 produktow.
https://projects.kodilla.com/browse/WDP200101-28
> Wdp200101 28

- src/App.js
- src/components/common/BlogBox/BlogBox.js
- src/components/common/BlogBox/BlogBox.module.scss
- src/components/features/LatestBlog/LatestBlog.js
- src/components/features/LatestBlog/LatestBlogContainer.js
- src/components/views/BlogPage/BlogPage.js
- src/redux/initialState.js
Dodałem route do pojedynczego bloga oraz zmieniłem initial state.
Troche namieszałem z gitem wiec na jednym pr są dwa zadania
https://projects.kodilla.com/browse/WDP200101-65
https://projects.kodilla.com/browse/WDP200101-67
> WDP200101-65

- src/App.js
- src/components/features/LatestBlog/LatestBlog.module.scss
- src/components/layout/MenuBar/MenuBar.js
- src/components/layout/ProductListBar/ProductListBar.module.scss
- src/components/views/ProductList/ProductList.js
- src/components/views/ProductList/ProductList.module.scss
- src/components/views/ProductList/ProductList.test.js
- src/components/views/ProductList/ProductListContainer.js
- src/components/views/ProductPage/ProductPage.test.js
- src/redux/productsRedux.js
https://projects.kodilla.com/browse/WDP200101-47
Zadnie miało na celu po kliknięciu w menu w jedną za kategorii produktów: Furniture, Chair, Table, Sofa czy Bedroom przechodzi do widoku listy produktów w danej kategorii.
W przypadku podania błędnego URL-a adresu wyświetla się strona Page Not Found i pozwala wrócić na stronę główną.
W pierwszym commicie pojawia się błąd.
> WDP200110-47v3

- src/components/common/BlogBox/BlogBox.module.scss
- src/components/features/LatestBlog/LatestBlog.module.scss
https://projects.kodilla.com/browse/WDP200101-60
Wyświetlane przyciski "READ MORE" w BlogBoxach wyświetlane są na jednym poziomie niezależnie od ilości tekstu w danym BlogBoxie.
> WDP200101-60v2

- src/components/common/GalleryBox/GalleryBox.module.scss
- src/components/features/Gallery/Gallery.js
- src/components/features/Gallery/Gallery.module.scss
Zadaniem jest stworzenie wersji mobilnych sekcji "Galeria".
Na telefonach pokazujemy tylko taby ze sliderem.
https://projects.kodilla.com/browse/WDP200101-29
> Wdp200101 29v2
